"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(user)/components/header";
import AnimatedCursor from "react-animated-cursor";
import { usePathname } from "next/navigation";
import React from "react";
import { FloatingDock } from "@/components/ui/floating-dock";
import { FloatingDockDemo } from "@/components/ui/floating-nav";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimatedCursor
          innerSize={8}
          outerSize={8}
          color="255, 165, 0"
          outerAlpha={0.2}
          innerScale={0.7}
          outerScale={5}
          clickables={[
            "a",
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            "label[for]",
            "select",
            "textarea",
            "button",
            ".link",
            {
              target: ".custom",
              options: {
                innerSize: 12,
                outerSize: 12,
                color: "255, 165, 0",
                outerAlpha: 0.3,
                innerScale: 0.7,
                outerScale: 5,
              },
            },
          ]}
        />
        {pathname === "/" && <>{children}</>}
        {pathname != "/" && (
          <>
            <Header />
            {children}
            <FloatingDockDemo/>
          </>
        )}
      </body>
    </html>
  );
}
